export const randomPrompts = [
  "Un bouquet de fleurs colorées sur une table en bois rustique, éclairé par une lumière naturelle douce.",
  "Un paysage urbain nocturne avec des gratte-ciels illuminés, reflétés dans les eaux calmes d'une rivière.",
  "Un café cosy avec des tasses de café fumantes, des pâtisseries fraîchement préparées et un intérieur chaleureux.",
  "Un arc-en-ciel vibrant s'étendant à travers un ciel nuageux après une averse.",
  "Une plage tropicale paradisiaque avec des palmiers, du sable blanc et des eaux turquoises.",
  "Un enfant riant aux éclats alors qu'il joue avec des bulles de savon dans un jardin ensoleillé.",
  "Une vue aérienne d'une ville animée, avec des rues enchevêtrées, des voitures et des passants.",
  "Un magnifique coucher de soleil surplombant un champ de lavande en pleine floraison.",
  "Une scène d'hiver enneigée, avec des sapins recouverts de neige et des flocons qui tombent lentement.",
  "Un marché animé avec des étals colorés remplis de fruits frais, de légumes et de fleurs.",
  "Une cascade impétueuse qui se précipite dans un canyon profond entouré de roches escarpées.",
  "Un couple heureux se promenant main dans la main le long d'une plage déserte au coucher du soleil.",
  "Un adorable chiot jouant avec une balle dans un parc verdoyant par une belle journée ensoleillée.",
  "Un intérieur moderne et minimaliste avec un mobilier design, des grandes baies vitrées et une décoration épurée.",
  "Une forêt mystérieuse et luxuriante, baignée par les rayons filtrés du soleil à travers le feuillage.",
  "Une vue aérienne d'une île tropicale isolée, entourée d'eaux cristallines et de récifs coralliens.",
  "Un champ de coquelicots écarlates s'étendant à perte de vue, créant un contraste éclatant avec le ciel bleu.",
  "Un groupe d'amis partageant un pique-nique joyeux dans un parc, entouré de couvertures et de paniers remplis de nourriture délicieuse.",
  "Un carnaval animé avec des manèges colorés, des lumières clignotantes et une atmosphère festive.",
  "Un lever de soleil spectaculaire surplombant un lac calme, avec des montagnes majestueuses à l'horizon.",
];
